### PR TITLE
Fixed task.configure() method to work with new associations architecture

### PR DESCRIPTION
**Pull request by wilcoschoneveld**

### CODE REVIEW

**Comment by wilcoschoneveld** [comment]
@jberends can you test and merge? :pray:

**Comment by wilcoschoneveld** [comment]
@jberends continuous integration fails because I didn't record a proper cassette in this branch, but you can test it with a live KE-chain server. I'm revising the tests in #65

**Comment by jberends** [comment]
Will check it out this morning @wilcoschoneveld

**Comment by jberends** [comment]
I am only wondering how we can maintain compatibility with older KEC releases in the field. This is only working for post sprint 119 deployments.

Can't we decorate with a warning or a legacy flag to enforce using the 'oldstyle' associations updater?

what do you think @wilcoschoneveld , @BennievanderWel

**Comment by wilcoschoneveld** [comment]
To keep things simple I would suggest to keep everything up-to-date and revert back to previous versions of pykechain if backwards compatibility is required. Do you foresee any problems in the near future regarding this?

**Comment by jberends** [comment]
yes, I foresee problems as the 119 sprint branch code is not deployed to many commercial instances (yet). Also not merged to RND instances because of the many changes due to the new assoc architecture. So there is no need (now) to include it into the 1.5.0 release.

**Comment by wilcoschoneveld** [comment]
Alright, I understand. But I do think its best to keep pykechain up to date as much as possible.

Suggestion: we keep pykechain up to date with latest KE-chain version and this is reflected in all tests. With something like a legacy flag or environment variable (investigation required) we can allow interaction with older versions of KE-chain, but this is not tested in continuous integration etc.

Alternatively, we could go for an approach where pykechain asks KE-chain for its version upon initial connection and with logical conditions we can execute the correct requests. I'm guessing this will require a lot more time to set up properly.

also, @BennievanderWel your thoughts are more than welcome!

**Comment by jberends** [comment]
As we have the 119 release already in the field for a month, we will include the backwards incompatibility change on the configuration of associations. This works and is test against the latest KE-chain-2 release (120 sprint-branch). Also works in April releases of the RND instances.

**Pull request merged**
