### PR TITLE
128-increase-tests-coverage

### PR DESCRIPTION
**Pull request by raduiordache**
- increased test coverage for scope.py to 95%
- increased test coverage for select list property to 100%

### CODE REVIEW

**Comment by raduiordache** [comment]
@jberends I have taken the liberty to further increase the coverage of some tests in pykechain. Some main topics that I notice on which we can further improve in the future:
- some methods are called within other methods, such as add_property() and create_property(). create_property() is used on the client and the part it belongs to needs to pass as an argument. On the other hand, add_property() is used on the part. However, what add_property does is basically just allowing more flexibility in property creation, as it just calls create_property(). 

There are more examples like this. I don't find any problem with it, but I believe that any tests written should be written on the higher method (add_property in this case). Since that method calls create_property(), then both of them will be tested and covered in just one go. Hence I refactored some code where this was not the case.

Also, I have removed code from coverage, mainly the __repr__() methods and the conditionals that check if the correct request code is returned (and if not, triggered an APIError).

**Comment by jberends** [comment]
added come 'review' comments. Lets discuss this tomorrow. Good initiatieve `B 124 RDU`

**Comment by raduiordache** [comment]
@jberends  Dank u wel! Added also 2 more tests for activity which now pushed the coverage past 95%!  :ok_hand:

**Comment by raduiordache** [comment]
@jberends 
Dank u wel! Added also 2 more tests for activity which now pushed the coverage past 95%!  :ok_hand: 

The only class left to tackle is the AttachmentProperty, which is only 66% covered up until now. However, I feel it might be a bit tricky to bring it to 100%. I will investigate further in the coming days.

**Pull request merged**
