### PR TITLE
523 - associated_parts() on Activity is back

### PR DESCRIPTION
**Pull request by raduiordache**
- made Activity.associated_parts() great again;
- looping through the widget and calling widget.parts()

### CODE REVIEW

**Comment by raduiordache** [comment]
Hi @jberends,

So I have re-added the possibility to call the associated_parts() on activity. The only issue which I don't know if we can solve is that since the parts are now associated to widgets, it might happen that on activity you have the same part associated multiple times. However, I think it's important that we still retrieve them every time they appear, mainly because the properties might be there in a widget and might not be there in the other, or they might be inputs in one and outputs in the other. Therefore it is important that the developer gets all of them correctly and it is his responsibility to make a set out of them if he needs it as such. 

What do you think about this?

**Comment by jberends** [comment]
refers to #523

**Comment by raduiordache** [comment]
@jberends - tests have been fixed;
- I have also added an Activity.associated_object_ids() function in order to extract the Associations filtered by that activity;
- It basically returns a list of dicts(), each dict representing a Property instance id, but providing information such as Part instance, Part model, Property model ids, etc. They are left as id's, as I feel this will allow the developer to make the calls he needs and parse it as required, while the Pykechain call is light.

**Comment by raduiordache** [comment]
@jberends , can you please review this? would be nice to get it into next version of Pykechain.

**Pull request merged**
