### PR TITLE
[wip] test framework revisited

### PR DESCRIPTION
**Pull request by wilcoschoneveld**

### CODE REVIEW

**Comment by wilcoschoneveld** [comment]
If the local `TEST_URL` is different from what was used to record a cassette, there can be conflicts. One example of this is when the response of the server includes a `next` url for use in batching, where the host path is then stored directly. In betamax, the server response is encoded in a base64-like format but it looks like the placeholders (such as TEST_URL) are not used there. A solution to this would be to built a [custom matcher](http://betamax.readthedocs.io/en/latest/matchers.html#making-your-own-matcher)

**Comment by wilcoschoneveld** [comment]
Almost there! However still some problems:

The default betamax matcher works by matching uri and method. It seems that the order of parameters in the generated requests urls is not always the same for pykechain and therefore betamax has trouble matching.

Another problem is that create_activity uses the same uri even if the target parent process is different, so betamax only records one of the requests and reuses it for both, resulting in failing tests.

I guess building a custom matcher (as suggested in the previous comment) is the solution. The matcher would have to match on url, method and json body. @jberends do you agree?

**Comment by jberends** [comment]
@wilcoschoneveld - sound clear. You might want to check the [`assertDictEqual()`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertDictEqual) for inspiration of matching dicts (the query/body part of the request)

**Comment by wilcoschoneveld** [comment]
Another testcase which fails:
1. Retrieve a part
2. Change something in the part
3. Retrieve part again
4. Check if change is applied correctly

Essentially step 1 and 3 are the same request so betamax will only save one response. There is no distinction in the request, so a custom matcher will not solve this. :confused:

**Comment by jberends** [comment]
Add a custom cache buster in the query for the test? Any additional query kwarg will suffice

**Comment by wilcoschoneveld** [comment]
slowly getting somewhere... still some issues remaining

**Comment by jberends** [comment]
we need to review this effort again as there are a lot of things changed in the latests code... Or... we need to close this
@wilcoschoneveld

**Comment by jberends** [comment]
in the mean time we are way ahead and ideas of this PR are incorporated in the recent way we do testing. Closing it down and removing the branch and PR.

**Pull request closed without merging**
