### PR TITLE
added add/remove supervisor member management methods on `Scope`

### PR DESCRIPTION
**Pull request by jberends**
* added supervisor in the scope enums
* added version check to see if backend is capable enough to handle the supervisor user member userrole.
* updated changelog

### CODE REVIEW

**Comment by jberends** [comment]
@JelleBoersma can you check this commit -- it is 'in the blind' as the backend is not in place for tests yet.

**Comment by JelleBoersma** [comment]
@raduiordache  I'd merge in master before trying anything else

**Comment by raduiordache** [comment]
> @raduiordache I'd merge in master before trying anything else

Mission accomplished

**Comment by raduiordache** [comment]
Temporary removed the cassettes as those tests were failing. Need to rerun the tests (with cassettes on) of the `TestScopeMembers` class, once the back-end on pim3-test is on par.

**Pull request merged**
